FROM node:22-alpine
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

CMD [ "npm", "run", "dev" ]








# Commands:
# 1. Show Images:
#   docker image ls
  
# 2. Show containers
#   docker ps
   
# 3. Build Image:
#   docker build -t britto-client .
  
# 4. Run a container:
#   docker run -p 5173:5173 -d --name britto-client-cnt1 britto-client

# 5. Delete a running container or container and all associated volumes:
#   docker rm britto-client-cnt1 -f
#   docker rm britto-client-cnt1 -fv 

# 6. Run by Mounting Volume: host:container
#   docker run -v $(pwd)/src:/app/src -p 5173:5173 -d --name britto-client-cnt1 britto-client

# 7. Mount volume but ignore node_modules - if we dlt node_modules in host.
#   docker run -v $(pwd)/src:/app/src -v /app/node_modules -p 5173:5173 -d --name britto-client-cnt1 britto-client

# 7. Read Only BindMount - we can't create files in dockerbash and sync with host
#   docker run -v $(pwd):/app:ro -v /app/node_modules -p 5173:5173 -d --name britto-client-cnt1 britto-client

# 8. Go inside Docker /app dir in Bash:
#   docker exec -it britto-client bash 

# 9. List all docker volumes:
#   docker volume ls 

# 10. Deleted Unused docker volumes:
#   docker volume prune