export const safeAuthUserSelect = {
  id: true,
  name: true,
  email: true,
  roll: true,
  phoneNumber: true,
  selfie: true,
  idCardFront: true,
  idCardBack: true,
  ipAddress: true,
  latitude: true,
  longitude: true,
  role: true,
  emailVerified: true,
  isVerified: true,
  brittooVerified: true,
  securityScore: true,
  isSuspended: true,
  suspensionCount: true,
  createdAt: true,
  updatedAt: true,
  isValidRuetMail: true,
};
